// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sogou/speech/asr/v1/webhook.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SPBWebhookRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SPBWebhookRoot : GPBRootObject
@end

#pragma mark - SPBRecognitionResultHookConfig

typedef GPB_ENUM(SPBRecognitionResultHookConfig_FieldNumber) {
  SPBRecognitionResultHookConfig_FieldNumber_Name = 1,
  SPBRecognitionResultHookConfig_FieldNumber_Uri = 2,
  SPBRecognitionResultHookConfig_FieldNumber_Extra = 3,
};

/**
 * Config a webhook when speech recoginition reaches a final result.
 **/
@interface SPBRecognitionResultHookConfig : GPBMessage

/**
 * this hook name. when hook call complete, the extra field of SpeechRecognitionResult or StreamingRecognitionResult will
 * be filled by a key-value pair, the content is hook result, and key will be set to this name.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** the hook uri, the SpeechRecognitionResult will be jsonize and post to this uri */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

/** *Optional* Other params will be set on the headers when post */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
