source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

xcodeproj 'asr-iOS-sdk.xcodeproj'

install! 'cocoapods', :deterministic_uuids => false

target 'asr-iOS-sdk' do
    # Depend on the generated SogouSpeech library.
    pod 'SogouSpeech', :path => '.'
end
 
